# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukWJSETmhkygHEnnfo-o-bvbhQNSb-ba
"""

from google.colab import auth


import gspread
from google.auth import default

import pandas as pd
from gspread_dataframe import set_with_dataframe , get_as_dataframe

class GoogleSheet:
    def __init__(self):
        auth.authenticate_user()
        creds, _ = default()
        self.gc = gspread.authorize(creds)

    def connect_with_spreadsheet(self,url_or_name):
        self.url_or_name=url_or_name

        if self.url_or_name.startswith('https://'):
            self.spreadsheet = self.gc.open_by_url(self.url_or_name)
        else:
            self.spreadsheet = self.gc.open(self.url_or_name)
        print('Conexión lista')
    def get_data(self,sheet_name):


        self.sheet_name=sheet_name#.replace() \xa0



        self.ws=self.spreadsheet.worksheet(self.sheet_name)
        return get_as_dataframe(self.ws)
    def get_sheet_names(self):
        return list(map(lambda x: x.title,self.spreadsheet.worksheets()))
    def save_data(self,df,sheet_name,rows="5000", cols="20"):
        try:
            self.spreadsheet.add_worksheet(title=sheet_name, rows=rows,cols=cols)

        except:
            pass
        finally:
            new_ws=spreadsheet.worksheet(sheet_name)
            set_with_dataframe(new_ws,df)